version: "3.8"

services:

  # Jupyter Notebook - PySpark Enabled
  jupyter-spark:

        build:
            context: lakehouse/jupyter
        hostname: myjupyter
        container_name: jupyter_container
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ./notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/
          - ./spark/conf:/usr/local/spark/conf
        restart: always
        depends_on:
                - postgres

  # Spark Master with 3 workers.
  spark-master:
    image: 'bde2020/spark-master:3.2.0-hadoop3.2'
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark/app:/usr/local/spark/app
      - ./spark/resources:/usr/local/spark/resources
    ports:
       - "8181:8080"
       - "7077:7077"
    networks:
      - oasiscorp

  # Spark Worker-1
  spark-worker-1:
    image: 'bde2020/spark-worker:3.2.0-hadoop3.2'
    container_name: spark-worker-1
    depends_on: 
      - spark-master
    ports:
      - "8081:8081"
    env_file:
      - spark.env
    volumes:
      - ./spark/app:/usr/local/spark/app 
      - ./spark/resources:/usr/local/spark/resources
    networks:
      - oasiscorp 

  # Spark Worker-2
  spark-worker-2:
    image: 'bde2020/spark-worker:3.2.0-hadoop3.2'
    container_name: spark-worker-2
    ports:
      - "8083:8081"
    depends_on: 
      - spark-master
    env_file:
      - spark.env
    volumes:
      - ./spark/app:/usr/local/spark/app
      - ./spark/resources:/usr/local/spark/resources
    networks:
      - oasiscorp
  
  # Spark Worker-3
  spark-worker-3:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-3
    ports:
      - "8084:8081"
    depends_on: 
      - spark-master
    env_file:
      - spark.env
    volumes:
      - ./spark/app:/usr/local/spark/app
      - ./spark/resources:/usr/local/spark/resources
    networks:
      - oasiscorp



# Network Bridge Connection
networks:
  oasiscorp:
    name: oasiscorp
    driver: bridge