version: "3"
services:

    # object storage
    minio:
        hostname: myminio
        container_name: minio_container
        image: 'bitnami/minio:latest' # latest image 
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: miniosecret
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - './minio/data:/data'
        networks:
            - oasiscorp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myminio:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        restart: always


    # Spark with 3 workers
    spark:
        hostname: myspark
        container_name: spark_container
        image: bitnami/spark:latest 
        user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        networks:
            - oasiscorp
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ./spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        hostname: mysparkw1
        container_name: sw1_container
        image: bitnami/spark:latest
        user: root
        networks:
            - oasiscorp
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ./spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)

    spark-worker-2:
        hostname: mysparkw2
        container_name: sw2_container
        image: bitnami/spark:latest
        user: root
        networks:
            - oasiscorp
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ./spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)



    #Jupyter notebook
    jupyter-spark:
        hostname: myjupyter
        container_name: jupyter_container
        image: jupyter/pyspark-notebook:spark-3.1.2
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
          - "4040-4080:4040-4080"
        volumes:
          - ./notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/


networks:
  oasiscorp:
    driver: bridge