version: '3.8'
services:

  # # Jupyter notebook
  # jupyter-spark:
  #       hostname: myjupyter
  #       container_name: jupyter_container
  #       image: 'jupyter/pyspark-notebook:spark-3.2.1'
  #       networks:
  #           - oasiscorp
  #       ports:
  #         - "8888:8888"
  #       volumes:
  #         - ../notebooks:/home/jovyan/work/notebooks/
  #         - ../spark/resources/data:/home/jovyan/work/data/
  #         - ../spark/resources/jars:/home/jovyan/work/jars/
  #       restart: always

  # Spark Master with 3 workers.
  spark-master:
    image: 'bde2020/spark-master:3.3.0-hadoop3.3'
    container_name: spark-master
    ports:
      - "8181:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
        - ../spark/app:/usr/local/spark/app 
        - ../spark/resources:/usr/local/spark/resources 
    networks:
        - oasiscorp
    environment:
      - INIT_DAEMON_STEP=setup_spark
  
  # Spark Worker 1.
  spark-worker-1:
    image: 'bde2020/spark-worker:3.3.0-hadoop3.3'
    container_name: spark-worker-1
    depends_on:
      - spark-master
    # ports:
    #   - "8081:8081"
    volumes:
       - ../spark/app:/usr/local/spark/app 
       - ../spark/resources:/usr/local/spark/resources 
    networks:
        - oasiscorp
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  
  # Spark Worker 2.
  spark-worker-2:
    image: 'bde2020/spark-worker:3.3.0-hadoop3.3'
    container_name: spark-worker-2
    depends_on:
      - spark-master
    # ports:
    #   - "8082:8081"
    volumes:
        - ../spark/app:/usr/local/spark/app 
        - ../spark/resources:/usr/local/spark/resources
    networks:
        - oasiscorp
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  # Spark Worker 3.
  spark-worker-3:
    image: 'bde2020/spark-worker:3.3.0-hadoop3.3'
    container_name: spark-worker-3
    depends_on:
      - spark-master
    # ports:
    #   - "8083:8081"
    volumes:
        - ../spark/app:/usr/local/spark/app 
        - ../spark/resources:/usr/local/spark/resources 
    networks:
        - oasiscorp
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
     
networks:
  oasiscorp:
    driver: bridge

